### ISSUE TITLE
[Bug]: [vite] Internal server error: vite.createFilter is not a function

### ISSUE THREAD

**Issue by cffycls** [flipped-aurora/gin-vue-admin#1697]
### gin-vue-admin 版本

2.4.6

### Node 版本

v18.20 | v16.20.2 
pnpm 安装

### Golang 版本

go version go1.22.1 windows/amd64

### 是否依旧存在

可以

### bug描述

前端使用pnpm i安装依赖后npm run serve报错
```
17:47:45 [vite] Internal server error: vite.createFilter is not a function
  Plugin: vite:vue
  File: D:/work/gin-vue-admin-2024/web/src/main.js
      at D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\@vitejs+plugin-vue@5.0.4_vite@2.5.10_vue@3.4.21\node_modules\@vitejs\plugin-vue\dist\index.cjs:2807:16
      at ReactiveEffect.fn (D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\@vue+reactivity@3.4.21\node_modules\@vue\reactivity\dist\reactivity.cjs.js:998:13)
      at ReactiveEffect.run (D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\@vue+reactivity@3.4.21\node_modules\@vue\reactivity\dist\reactivity.cjs.js:181:19)
      at ComputedRefImpl.get value [as value] (D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\@vue+reactivity@3.4.21\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1010:109)
      at TransformContext.transform (D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\@vitejs+plugin-vue@5.0.4_vite@2.5.10_vue@3.4.21\node_modules\@vitejs\plugin-vue\dist\index.cjs:2918:19)
      at Object.transform (D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:50373:53)
      at async transformRequest (D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:65414:29)
      at async viteTransformMiddleware (D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:65542:32)
17:47:45 [vite] Internal server error: filter.value is not a function
  Plugin: vite:vue
  File: D:/work/gin-vue-admin-2024/web/node_modules/.pnpm/vite@2.5.10/node_modules/vite/dist/client/client.mjs
      at TransformContext.transform (D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\@vitejs+plugin-vue@5.0.4_vite@2.5.10_vue@3.4.21\node_modules\@vitejs\plugin-vue\dist\index.cjs:2918:19)
      at Object.transform (D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:50373:53)
      at async transformRequest (D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:65414:29)
      at async viteTransformMiddleware (D:\work\gin-vue-admin-2024\web\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:65542:32)
```

**Comment by pixelmaxQm** [comment]
node版本过低

**Comment by cffycls** [comment]
嗯，我使用main分支，重新安装环境就好了
