### ISSUE TITLE
[Bug]: 菜单每隔一次出现错误，

### ISSUE THREAD

**Issue by CodeListening** [flipped-aurora/gin-vue-admin#1723]
### gin-vue-admin 版本

2.5.7

### Node 版本

16

### Golang 版本

1.16

### 是否依旧存在

可以

### bug描述

1. 在开发环境不会出现，但是在生产环境 docker部署后会出现
2. 点击菜单栏选项每隔一次出现错误
`087AC4D233B64EB0index.js:22 TypeError: Cannot read properties of null (reading '0')
    at Wn (087AC4D233B64EB0index.js:22:9062)
    at Proxy.<anonymous> (087AC4D233B64EB0index.js:22:7500)
    at fn (087AC4D233B64EB0index.js:22:3193)
    at se.i [as fn] (087AC4D233B64EB0index.js:23:20388)
    at se.run (087AC4D233B64EB0index.js:17:1507)
    at F.e.update (087AC4D233B64EB0index.js:23:21263)
    at e.afterLeave (087AC4D233B64EB0index.js:22:7677)
    at a (087AC4D233B64EB0index.js:23:25116)
    at t.<computed> (087AC4D233B64EB0index.js:22:8817)
    at B (087AC4D233B64EB0index.js:23:36492)`

### 修改建议

推测是vue router 升级导致

**Comment by pixelmaxQm** [comment]
本地build 然后运行 npm run preview 看是否会出现

**Comment by bypanghu** [comment]
你这是自己业务代码的问题, gva demo 没出现肯定不是 gva 代码的问题

**Comment by pixelmaxQm** [comment]
![20240424181213_rec_](https://github.com/flipped-aurora/gin-vue-admin/assets/165128580/2a65877c-2450-45ce-a991-34114e30f0c1)
无法复现

**Comment by CodeListening** [comment]
不是gva的问题，是docker compose部署的时候，更新代码没有使用 --no-cache重新编译！！！！
