### ISSUE TITLE
[Bug]: 添加菜单失败

### ISSUE THREAD

**Issue by XRSec** [flipped-aurora/gin-vue-admin#941]
### gin-vue-admin 版本

latest

### Node 版本

docker-compose

### Golang 版本

docker-compose

### 是否依旧存在

可以

### bug描述

```log
userscript.html?name=%E8%AE%A1%E6%97%B6%E5%99%A8%E6%8E%8C%E6%8E%A7%E8%80%85%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E8%B7%B3%E8%BF%87%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E5%8A%A0%E9%80%9F%E5%99%A8.user.js&id=e5832578-2605-470f-a8e1-c885ea602bb0:2872 [TimeHooker] loading outer window...
userscript.html?name=%E8%AE%A1%E6%97%B6%E5%99%A8%E6%8E%8C%E6%8E%A7%E8%80%85%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E8%B7%B3%E8%BF%87%7C%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E5%8A%A0%E9%80%9F%E5%99%A8.user.js&id=e5832578-2605-470f-a8e1-c885ea602bb0:2357 Time Hooker Works!
gin-vue-admin-index.1646733026000.js:4 
       欢迎使用 Gin-Vue-Admin
       当前版本:V2.5.0
       加群方式:微信：shouzi_1994 QQ群：622360840
       GVA讨论社区:https://support.qq.com/products/371961
       默认自动化文档地址:http://127.0.0.1:8888/swagger/index.html
       默认前端文件运行地址:http://127.0.0.1:8080
       如果项目让您获得了收益，希望您能请团队喝杯可乐:https://www.gin-vue-admin.com/docs/coffee
    
DevTools 无法加载来源映射：无法加载 chrome-extension://dobbfkjhgbkmmcooahlnllfopfmhcoln/scripts/contentscript.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
gin-vue-admin-index.16467330260007.js:4 Proxy {0: 'SuperAdmin', 1: 'Menus', 2: 'Api', 3: 'System', 4: 'AutoCode', 5: 'FormGenerator'}
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at content_script.js:240:28
（匿名） @ content_script.js:240
postMessage（异步）
script.onload @ content.js:25
load（异步）
（匿名） @ content.js:10
inject @ content.js:6
getJs @ content.js:37
onGetTechnologies @ content.js:394
init @ content.js:289
await in init（异步）
（匿名） @ content.js:408
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at content_script.js:240:28
（匿名） @ content_script.js:240
postMessage（异步）
onMessage @ VM348 js.js:14
postMessage（异步）
script.onload @ content.js:25
load（异步）
（匿名） @ content.js:10
inject @ content.js:6
getJs @ content.js:37
onGetTechnologies @ content.js:394
init @ content.js:289
await in init（异步）
（匿名） @ content.js:408
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at content_script.js:240:28
（匿名） @ content_script.js:240
postMessage（异步）
script.onload @ content.js:25
load（异步）
（匿名） @ content.js:10
inject @ content.js:6
getDom @ content.js:50
onGetTechnologies @ content.js:395
await in onGetTechnologies（异步）
init @ content.js:289
await in init（异步）
（匿名） @ content.js:408
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at content_script.js:240:28
（匿名） @ content_script.js:240
postMessage（异步）
onMessage @ dom.js:17
postMessage（异步）
script.onload @ content.js:25
load（异步）
（匿名） @ content.js:10
inject @ content.js:6
getDom @ content.js:50
onGetTechnologies @ content.js:395
await in onGetTechnologies（异步）
init @ content.js:289
await in init（异步）
（匿名） @ content.js:408
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at content_script.js:240:28
（匿名） @ content_script.js:240
postMessage（异步）
script.onload @ content.js:25
load（异步）
（匿名） @ content.js:10
inject @ content.js:6
getJs @ content.js:37
init @ content.js:294
await in init（异步）
（匿名） @ content.js:408
content_script.js:240 Uncaught TypeError: Cannot read properties of undefined (reading 'eventType')
    at content_script.js:240:28
（匿名） @ content_script.js:240
postMessage（异步）
onMessage @ js.js:14
postMessage（异步）
script.onload @ content.js:25
load（异步）
（匿名） @ content.js:10
inject @ content.js:6
getJs @ content.js:37
init @ content.js:294
await in init（异步）
（匿名） @ content.js:408
gin-vue-admin-vendor.1646733026000.js:20 TypeError: Cannot use 'in' operator to search for 'displayName' in undefined
    at N6 (gin-vue-admin-vendor.1646733026000.js:20:13067)
    at gin-vue-admin-vendor.1646733026000.js:20:19395
E @ gin-vue-admin-vendor.1646733026000.js:20
（匿名） @ gin-vue-admin-vendor.1646733026000.js:20
Promise.catch（异步）
y @ gin-vue-admin-vendor.1646733026000.js:20
m @ gin-vue-admin-vendor.1646733026000.js:20
_ @ gin-vue-admin-index.16467330260008.js:4
qt @ gin-vue-admin-vendor.1646733026000.js:1
Wt @ gin-vue-admin-vendor.1646733026000.js:1
vn @ gin-vue-admin-vendor.1646733026000.js:1
g @ gin-vue-admin-vendor.1646733026000.js:15
handleClick @ gin-vue-admin-vendor.1646733026000.js:15
ma.onClick.t.<computed>.t.<computed> @ gin-vue-admin-vendor.1646733026000.js:15
qt @ gin-vue-admin-vendor.1646733026000.js:1
Wt @ gin-vue-admin-vendor.1646733026000.js:1
n @ gin-vue-admin-vendor.1646733026000.js:1
gin-vue-admin-vendor.1646733026000.js:20 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'displayName' in undefined
    at N6 (gin-vue-admin-vendor.1646733026000.js:20:13067)
    at gin-vue-admin-vendor.1646733026000.js:20:19395
N6 @ gin-vue-admin-vendor.1646733026000.js:20
（匿名） @ gin-vue-admin-vendor.1646733026000.js:20
Promise.then（异步）
y @ gin-vue-admin-vendor.1646733026000.js:20
m @ gin-vue-admin-vendor.1646733026000.js:20
_ @ gin-vue-admin-index.16467330260008.js:4
qt @ gin-vue-admin-vendor.1646733026000.js:1
Wt @ gin-vue-admin-vendor.1646733026000.js:1
vn @ gin-vue-admin-vendor.1646733026000.js:1
g @ gin-vue-admin-vendor.1646733026000.js:15
handleClick @ gin-vue-admin-vendor.1646733026000.js:15
ma.onClick.t.<computed>.t.<computed> @ gin-vue-admin-vendor.1646733026000.js:15
qt @ gin-vue-admin-vendor.1646733026000.js:1
Wt @ gin-vue-admin-vendor.1646733026000.js:1
n @ gin-vue-admin-vendor.1646733026000.js:1
```

**Comment by piexlmax** [comment]
感觉像是打包失败了

**Comment by XRSec** [comment]
打包啥？不懂，反正全Google网络运行的

**Comment by piexlmax** [comment]
提供一下复现步骤

**Comment by piexlmax** [comment]
@tscuite 看环境为docker-compose 中出现的  测试下是否存在该问题

**Comment by XRSec** [comment]
我人都麻了，迷茫了。。。

**Comment by XRSec** [comment]
```dockerfile
version: "3"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  web:
    # build:
    #   context: /Users/xr/IDEA/sslt/vue/web
    #   dockerfile: /Users/xr/IDEA/sslt/vue/web/Dockerfile
    image: sslt:web
    container_name: sslt-web
    hostname: sslt-web
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.11

  server:
    # build:
    #   context: /Users/xr/IDEA/sslt/vue/server
    #   dockerfile: /Users/xr/IDEA/sslt/vue/server/Dockerfile
    image: sslt:server
    container_name: sslt-server
    hostname: sslt-server
    restart: always
    ports:
      - '8888:8888'
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      network:
        ipv4_address: 177.7.0.12

  mysql:
    image: mysql:8.0.21
    container_name: sslt-mysql
    hostname: sslt-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'admin' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'admin' # root管理员用户密码
    networks:
      network:
        ipv4_address: 177.7.0.13

  redis:
    image: redis:6.0.6
    hostname: sslt-redis
    container_name: gva-redis # 容器名
    restart: always
    ports:
      - '16379:6379'
    networks:
      network:
        ipv4_address: 177.7.0.14
```

**Comment by XRSec** [comment]
![image](https://user-images.githubusercontent.com/73819467/157249031-47d1f87f-ed62-4f82-a85f-eadb02e4c8f2.png)
![image](https://user-images.githubusercontent.com/73819467/157249254-fb011aa7-aba7-412b-8c0d-cd58d1a44166.png)
![image](https://user-images.githubusercontent.com/73819467/157249290-6b028430-f0cc-41b0-a128-73aebb1a235b.png)
![image](https://user-images.githubusercontent.com/73819467/157249332-015c1845-1692-40dd-968b-e0bd4e4d9bad.png)


重启



![image](https://user-images.githubusercontent.com/73819467/157249741-06d11624-2e0a-41bd-a172-e925437fab90.png)

**Comment by tscuite** [comment]
给力，太详细了。。。

**Comment by XRSec** [comment]
我尝试了你们3个版本，好像都有这个问题，感觉像是我环境的问题,人都麻了:cry:

**Comment by tscuite** [comment]
> 我尝试了你们3个版本，好像都有这个问题，感觉像是我环境的问题,人都麻了😢

明天我会进行测试。。。请问是在添加了新的菜单文件以后才进行docker镜像制作的吗

**Comment by XRSec** [comment]
先镜像制作，再添加菜单

**Comment by tscuite** [comment]
> 先镜像制作，再添加菜单

。。。发现问题了，，得最后制作镜像

**Comment by tscuite** [comment]
> 先镜像制作，再添加菜单

可能你不太理解原理。。。就是用docker添加完菜单以后需要重新制作镜像。。。

**Comment by piexlmax** [comment]
开发期间不建议使用docker

**Comment by XRSec** [comment]
@tscuite 你看能不能我帮你们重新设计一套docker方案，你们帮我打包一套精简版的页面，就三个页面就够了

**Comment by XRSec** [comment]
是个体验 开发 部署的模版

**Comment by tscuite** [comment]
> @tscuite 你看能不能我帮你们重新设计一套docker方案，你们帮我打包一套精简版的页面，就三个页面就够了

这个可以添加weixin进入交流群里面沟通噢
https://camo.githubusercontent.com/8c0270d1bb44d6c04be0c87f797d898fd513e941d523b3a7f398cd567a157ac5/687474703a2f2f716d706c7573696d672e68656e726f6e6779692e746f702f71726a6a7a2e706e67
